# 3. docker/docker-compose.yml
version: '3'
services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.dockerfile
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    container_name: python-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ../backend:/app

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge